/**
 * Task Processor
 *
 * Handles background tasks and automated transitions.
 */

import type {
  ArtifactRepository,
  EventRepository,
  TaskRepository,
} from "./repositories/index.js";

export class TaskProcessor {
  constructor(
    private taskRepo: TaskRepository,
    private eventRepo: EventRepository,
    private artifactRepo: ArtifactRepository
  ) {}

  /**
   * Called when a task status changes
   */
  async onStatusChanged(taskId: number, from: string, to: string) {
    console.log(`[TaskProcessor] Task ${taskId} moved from ${from} to ${to}`);

    if (to === "IN_PROGRESS") {
      await this.handleInProgress(taskId);
    }
  }

  /**
   * Handle IN_PROGRESS transition
   */
  private async handleInProgress(taskId: number) {
    try {
      const task = await this.taskRepo.findById(taskId);
      if (!task) return;

      // 1. Create a "Technical Implementation Draft" artifact
      await this.createTechnicalDraft(
        taskId,
        task.title,
        task.description || ""
      );

      // 2. Update acceptance checklist if empty
      await this.initChecklist(taskId, task.acceptanceChecklist || []);
    } catch (err) {
      console.error(
        "[TaskProcessor] Failed to process In Progress transition:",
        err
      );
    }
  }

  /**
   * Create a technical implementation draft
   */
  private async createTechnicalDraft(
    taskId: number,
    title: string,
    description: string
  ) {
    const draftContent = `
# Implementation Plan: ${title}

## Objective
${description || "No description provided."}

## High-Level Approach
1. [ ] **Research**: Analyze current codebase for related components and state patterns.
2. [ ] **Architecture**: Plan the component structure (for frontend) or service logic (for backend).
3. [ ] **Execution**: Implement the core logic iteratively.
4. [ ] **Verification**: Run automated checks and perform manual validation.

## Locus Design Standards
- **Aesthetics**: Ensure the UI feels premium (gradients, glassmorphism, modern typography).
- **Interactivity**: Add subtle micro-animations and smooth transitions.
- **Standards**: Use local-first principles and strict type safety.

## Quality Gates
- [ ] Code follows project style guidelines and naming conventions.
- [ ] No regression in existing functionality.
- [ ] Documentation updated if necessary.
- [ ] Lint and Typecheck pass successfully.

---
*This draft was automatically generated by Locus to kickstart your implementation.*
`.trim();

    await this.artifactRepo.create({
      taskId,
      type: "TECH_DRAFT",
      title: `Draft: ${title}`,
      contentText: draftContent,
      createdBy: "system",
      createdAt: new Date(),
    });
  }

  /**
   * Initialize task checklist if empty
   */
  private async initChecklist(taskId: number, current: unknown[]) {
    if (current.length > 0) return; // Don't overwrite existing checklist

    const defaultChecklist = [
      { id: "step-1", text: "Research & Planning", done: false },
      { id: "step-2", text: "Implementation", done: false },
      { id: "step-3", text: "Testing & Verification", done: false },
      {
        id: `quality-lint-${Date.now()}`,
        text: "bun run lint",
        done: false,
      },
      {
        id: `quality-typecheck-${Date.now()}`,
        text: "bun run typecheck",
        done: false,
      },
    ];

    await this.taskRepo.update(taskId, {
      acceptanceChecklist: defaultChecklist,
    });

    await this.eventRepo.create({
      taskId,
      type: "CHECKLIST_INITIALIZED",
      payload: { itemCount: defaultChecklist.length },
      createdAt: new Date(),
    });
  }
}
