import { EventType } from "@locusai/shared";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";
import { Repository } from "typeorm";
import { Artifact, Task } from "@/entities";
import { EventsService } from "@/events/events.service";

@Injectable()
export class TaskProcessor {
  constructor(
    @InjectRepository(Task)
    private readonly taskRepository: Repository<Task>,
    @InjectRepository(Artifact)
    private readonly artifactRepository: Repository<Artifact>,
    private readonly eventsService: EventsService
  ) {}

  async onStatusChanged(taskId: string, _from: string, to: string) {
    if (to === "IN_PROGRESS") {
      await this.handleInProgress(taskId);
    }
  }

  private async handleInProgress(taskId: string) {
    try {
      const task = await this.taskRepository.findOne({ where: { id: taskId } });
      if (!task) return;

      // 1. Create a "Technical Implementation Draft" artifact
      await this.createTechnicalDraft(
        taskId,
        task.title,
        task.description || ""
      );

      // 2. Update acceptance checklist if empty
      await this.initChecklist(
        taskId,
        task.workspaceId,
        task.acceptanceChecklist || []
      );
    } catch (err) {
      console.error("[TaskProcessor] Error in handleInProgress:", err);
    }
  }

  private async createTechnicalDraft(
    taskId: string,
    title: string,
    description: string
  ) {
    const draftContent = `
# Implementation Plan: ${title}

## Objective
${description || "No description provided."}

## High-Level Approach
1. [ ] **Research**: Analyze current codebase for related components and state patterns.
2. [ ] **Architecture**: Plan the component structure (for frontend) or service logic (for backend).
3. [ ] **Execution**: Implement the core logic iteratively.
4. [ ] **Verification**: Run automated checks and perform manual validation.

## Locus Design Standards
- **Aesthetics**: Ensure the UI feels premium (gradients, glassmorphism, modern typography).
- **Interactivity**: Add subtle micro-animations and smooth transitions.
- **Standards**: Use local-first principles and strict type safety.

## Quality Gates
- [ ] Code follows project style guidelines and naming conventions.
- [ ] No regression in existing functionality.
- [ ] Documentation updated if necessary.
- [ ] Lint and Typecheck pass successfully.

---
*This draft was automatically generated by Locus to kickstart your implementation.*
`.trim();

    const artifact = this.artifactRepository.create({
      taskId,
      type: "TECH_DRAFT",
      title: `Draft: ${title}`,
      contentText: draftContent,
      createdBy: "system",
    });

    await this.artifactRepository.save(artifact);
  }

  private async initChecklist(
    taskId: string,
    workspaceId: string,
    current: Array<{ id: string; text: string; done: boolean }>
  ) {
    if (current && current.length > 0) return;

    const defaultChecklist = [
      { id: "step-1", text: "Research & Planning", done: false },
      { id: "step-2", text: "Implementation", done: false },
      { id: "step-3", text: "Testing & Verification", done: false },
      {
        id: `quality-lint-${Date.now()}`,
        text: "bun run lint",
        done: false,
      },
      {
        id: `quality-typecheck-${Date.now()}`,
        text: "bun run typecheck",
        done: false,
      },
    ];

    await this.taskRepository.update(taskId, {
      acceptanceChecklist: defaultChecklist,
    });

    await this.eventsService.logEvent({
      workspaceId,
      taskId,
      type: EventType.CHECKLIST_INITIALIZED,
      payload: { itemCount: defaultChecklist.length },
    });
  }
}
