export enum UserRole {
  USER = "USER",
  ADMIN = "ADMIN",
}

export enum MembershipRole {
  OWNER = "OWNER",
  ADMIN = "ADMIN",
  MEMBER = "MEMBER",
  VIEWER = "VIEWER",
}

export enum TaskStatus {
  BACKLOG = "BACKLOG",
  IN_PROGRESS = "IN_PROGRESS",
  REVIEW = "REVIEW",
  VERIFICATION = "VERIFICATION",
  DONE = "DONE",
  BLOCKED = "BLOCKED",
}

export enum TaskPriority {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
}

export enum AssigneeRole {
  BACKEND = "BACKEND",
  FRONTEND = "FRONTEND",
  QA = "QA",
  PM = "PM",
  DESIGN = "DESIGN",
}

export enum SprintStatus {
  PLANNED = "PLANNED",
  ACTIVE = "ACTIVE",
  COMPLETED = "COMPLETED",
}

export enum EventType {
  TASK_CREATED = "TASK_CREATED",
  TASK_UPDATED = "TASK_UPDATED",
  TASK_DELETED = "TASK_DELETED",
  STATUS_CHANGED = "STATUS_CHANGED",
  COMMENT_ADDED = "COMMENT_ADDED",
  CI_RAN = "CI_RAN",
  WORKSPACE_CREATED = "WORKSPACE_CREATED",
  MEMBER_ADDED = "MEMBER_ADDED",
  MEMBER_INVITED = "MEMBER_INVITED",
  SPRINT_CREATED = "SPRINT_CREATED",
  SPRINT_STATUS_CHANGED = "SPRINT_STATUS_CHANGED",
  SPRINT_DELETED = "SPRINT_DELETED",
  CHECKLIST_INITIALIZED = "CHECKLIST_INITIALIZED",
  INTERVIEW_STARTED = "INTERVIEW_STARTED",
  INTERVIEW_FIELD_COMPLETED = "INTERVIEW_FIELD_COMPLETED",
  INTERVIEW_COMPLETED = "INTERVIEW_COMPLETED",
  INTERVIEW_ABANDONED = "INTERVIEW_ABANDONED",
}
