export enum UserRole {
  USER = "USER",
  ADMIN = "ADMIN",
}

export enum MembershipRole {
  OWNER = "OWNER",
  ADMIN = "ADMIN",
  MEMBER = "MEMBER",
  VIEWER = "VIEWER",
}

export enum TaskStatus {
  BACKLOG = "BACKLOG",
  IN_PROGRESS = "IN_PROGRESS",
  IN_REVIEW = "IN_REVIEW",
  BLOCKED = "BLOCKED",
  DONE = "DONE",
}

export enum TaskPriority {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
}

export enum AssigneeRole {
  BACKEND = "BACKEND",
  FRONTEND = "FRONTEND",
  QA = "QA",
  PM = "PM",
  DESIGN = "DESIGN",
}

export enum SprintStatus {
  PLANNED = "PLANNED",
  ACTIVE = "ACTIVE",
  COMPLETED = "COMPLETED",
}

export enum EventType {
  TASK_CREATED = "TASK_CREATED",
  TASK_UPDATED = "TASK_UPDATED",
  TASK_DELETED = "TASK_DELETED",
  STATUS_CHANGED = "STATUS_CHANGED",
  COMMENT_ADDED = "COMMENT_ADDED",
  CI_RAN = "CI_RAN",
  WORKSPACE_CREATED = "WORKSPACE_CREATED",
  MEMBER_ADDED = "MEMBER_ADDED",
  MEMBER_INVITED = "MEMBER_INVITED",
  SPRINT_CREATED = "SPRINT_CREATED",
  SPRINT_STATUS_CHANGED = "SPRINT_STATUS_CHANGED",
  SPRINT_DELETED = "SPRINT_DELETED",
  CHECKLIST_INITIALIZED = "CHECKLIST_INITIALIZED",
  AGENT_HEARTBEAT = "AGENT_HEARTBEAT",
  TASK_DISPATCHED = "TASK_DISPATCHED",
  PR_CREATED = "PR_CREATED",
  PR_REVIEWED = "PR_REVIEWED",
  PR_MERGED = "PR_MERGED",
}

export enum SecurityAuditEventType {
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAILURE = "LOGIN_FAILURE",
  OTP_REQUEST = "OTP_REQUEST",
  OTP_VERIFY_SUCCESS = "OTP_VERIFY_SUCCESS",
  OTP_VERIFY_FAILURE = "OTP_VERIFY_FAILURE",
  OTP_BRUTE_FORCE_LOCKOUT = "OTP_BRUTE_FORCE_LOCKOUT",
  AUTH_FAILURE = "AUTH_FAILURE",
  API_KEY_CREATED = "API_KEY_CREATED",
  API_KEY_DELETED = "API_KEY_DELETED",
}
